### ISSUE TITLE
Custom page size and orientation issue

### ISSUE THREAD

**Issue by Notanotherdotcom** [wanze/Pages2Pdf#1]
Hi there

Love the WirePDF module, but I want to set a custom page size in landscape orientation to print to a label printer. The current implementation prepends the page size to the letter L in landscape, so "A4-L", but you can set custom page sizes in mPDF in millimetres like this: $pdf->pageFormat = array(54,20);

My issue of course is that I need to print landscape onto that label now.

Looking at the docs on the mPDF, it seems to suggest that orientation can be set separately rather than as '-L' on the end - is this possible?

Also, can I suggest that WirePDF be released as a separate module and that PagesPDF require it instead? There are a lot of cases where I want to use WirePDF but I don't yet have a need for PagesPDF.

**Comment by wanze** [comment]
Hi Pete,
There is a bug in mPDF that resets the landscape orientation to portrait in the constructor. Landscape only worked when I passed it prepended to the format. It seems I've found a workaround for this by passing the orientation again when adding a page.
Can you grab the latest version of WirePDF here and check if it works for you?

You're right, WirePDF should be a separate module. The reason I included it into Pages2Pdf is that I wanted a simple update scenario for the users of the previous version. But it just makes more sense to split them up :)

Cheers
