### ISSUE TITLE
mpdf/tmp folder

### ISSUE THREAD

**Issue by joey102030** [wanze/Pages2Pdf#2]
I love this module.

You included a note about giving 3 folders write permissions, but the thing that tripped me up was you haven't actually included the mpdf/tmp folder in the your file structure, so I missed it completely and it caused a readdir error in my code.

Not a huge issue, just something that could make this even more perfect!

**Comment by wanze** [comment]
Thanks!

Can you point me where I added the notes about giving the write permissions?

You're right, the tmp folder is missing in the file structure. Ideally the temp folder would be the same as ProcessWire uses, so write permission would be guaranteed.
It seems possible to set a custom temp folder: http://mpdf1.com/manual/index.php?tid=445&searchstring=temp
Looks a bit old school but if it works I will update it with the next version. :)

Thanks for the information!

**Comment by joey102030** [comment]
https://github.com/wanze/Pages2Pdf/blob/master/mpdf/README.txt
Line 6

Yeh I think the best solution would ultimately be to use PW cache folder
