### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by jlahijani** [wanze/Pages2Pdf#5]
When trying to install the following error occurs:
"ProcessModule: Module is not installable because not all required dependencies are currently met."

![2015-04-16_9-49-51](https://cloud.githubusercontent.com/assets/4558/7186364/fda98cac-e41d-11e4-8e2a-c53007f59162.jpg)

**Comment by PeterKnightDigital** [comment]
Do you see a module called WirePDF in your modules ? Install that first.

**Comment by jlahijani** [comment]
OK... I see the problem now.

If I install the module by uploading the zip, it will first give me the option to install the WirePDF module first.

However, if I install the module using PW's "Add Module From Directory" option (which is what I normally do), it results in the error screenshot I posted.

There's probably some logic needed for that situation.

**Comment by wanze** [comment]
It seems that ProcessWire can't (yet) handle this situation, I will do some testing and open an issue. This may be tricky to implement because the dependent module could be either included in the same package or existing as separate github repo.
